// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseConnection() {
  return window['go']['wailsbridge']['Bridge']['CloseConnection']();
}

export function CreateRoom() {
  return window['go']['wailsbridge']['Bridge']['CreateRoom']();
}

export function EmitNetworkError(arg1) {
  return window['go']['wailsbridge']['Bridge']['EmitNetworkError'](arg1);
}

export function EmitSecurityMessage(arg1) {
  return window['go']['wailsbridge']['Bridge']['EmitSecurityMessage'](arg1);
}

export function FindRoom(arg1) {
  return window['go']['wailsbridge']['Bridge']['FindRoom'](arg1);
}

export function GetNetworkStatus() {
  return window['go']['wailsbridge']['Bridge']['GetNetworkStatus']();
}

export function GetPeerFingerprint() {
  return window['go']['wailsbridge']['Bridge']['GetPeerFingerprint']();
}

export function GetRoomAccessKey() {
  return window['go']['wailsbridge']['Bridge']['GetRoomAccessKey']();
}

export function GetSecuritySummary() {
  return window['go']['wailsbridge']['Bridge']['GetSecuritySummary']();
}

export function GetUserID() {
  return window['go']['wailsbridge']['Bridge']['GetUserID']();
}

export function JoinRoom(arg1, arg2, arg3) {
  return window['go']['wailsbridge']['Bridge']['JoinRoom'](arg1, arg2, arg3);
}

export function JoinRoomWithFallback(arg1, arg2) {
  return window['go']['wailsbridge']['Bridge']['JoinRoomWithFallback'](arg1, arg2);
}

export function JoinUserByID(arg1, arg2) {
  return window['go']['wailsbridge']['Bridge']['JoinUserByID'](arg1, arg2);
}

export function RegenerateRoomAccessKey() {
  return window['go']['wailsbridge']['Bridge']['RegenerateRoomAccessKey']();
}

export function SendMessage(arg1) {
  return window['go']['wailsbridge']['Bridge']['SendMessage'](arg1);
}

export function SetContext(arg1) {
  return window['go']['wailsbridge']['Bridge']['SetContext'](arg1);
}

export function UpdateNickname(arg1) {
  return window['go']['wailsbridge']['Bridge']['UpdateNickname'](arg1);
}
