// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CloseConnection():Promise<void>;

export function CreateRoom():Promise<Record<string, any>>;

export function EmitNetworkError(arg1:Error):Promise<void>;

export function EmitSecurityMessage(arg1:string):Promise<void>;

export function FindRoom(arg1:string):Promise<Record<string, any>>;

export function GetNetworkStatus():Promise<Record<string, any>>;

export function GetPeerFingerprint():Promise<string>;

export function GetRoomAccessKey():Promise<string>;

export function GetSecuritySummary():Promise<Record<string, any>>;

export function GetUserID():Promise<string>;

export function JoinRoom(arg1:string,arg2:string,arg3:string):Promise<void>;

export function JoinRoomWithFallback(arg1:string,arg2:string):Promise<void>;

export function JoinUserByID(arg1:string,arg2:string):Promise<void>;

export function RegenerateRoomAccessKey():Promise<string>;

export function SendMessage(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateNickname(arg1:string):Promise<void>;
